version: '3'
services:
  mysql:
    hostname: mysql
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    command: --default-authentication-plugin=mysql_native_password
    volumes:
       - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  redis:  
    hostname: redis
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass 123456 --appendonly yes
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"

  server_api:
    build: ./server_api
    depends_on:
      - mysql
      - redis
    ports:
      - "3333:3333"

  server_inventory:
    build: ./server_inventory
    depends_on:
      - mysql
      - redis
    ports:
      - "4444:3333"

  client_admin:
    build: ./client_admin
    depends_on:
      - server_api
    ports:
      - "8080:80"

  client_shop:
    build: ./client_shop
    depends_on:
      - server_api
    ports:
      - "8081:80"