FROM node:14.18

COPY ./ /home/client_admin

WORKDIR /home/client_admin

RUN npm install

RUN npm run build

# Nginx代理
FROM nginx:alpine

RUN mkdir /home/client_admin

COPY --from=0 /home/client_admin/dist /home/client_admin

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]