FROM node:14.18

COPY ./ /home/client_shop

WORKDIR /home/client_shop

RUN npm install

RUN npm run build

# Nginx代理
FROM nginx:alpine

RUN mkdir /home/client_shop

COPY --from=0 /home/client_shop/dist /home/client_shop

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]